// <auto-generated />
using System;
using System.Text.Json;
using HeadlessCms.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeadlessCms.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeadlessCms.Api.Auth.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("HeadlessCms.Api.Auth.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PlatformRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlatformRole")
                        .IsUnique()
                        .HasFilter("\"PlatformRole\" = 'PlatformAdmin'");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTypeVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "ContentTypeId", "ContentTypeVersionId");

                    b.HasIndex("TenantId", "ProjectId", "ContentTypeId", "Status", "CreatedAt");

                    b.ToTable("ContentEntries");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTypeVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Nullable")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<JsonElement>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "ContentTypeVersionId", "Key")
                        .IsUnique();

                    b.ToTable("ContentFields");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "Key")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProjectId", "Id", "CurrentVersionId");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "ContentTypeId", "Version")
                        .IsUnique();

                    b.ToTable("ContentTypeVersions");
                });

            modelBuilder.Entity("HeadlessCms.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.TenantInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcceptedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("TenantInvitations");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.TenantMembership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Role")
                        .IsUnique()
                        .HasFilter("\"Role\" = 'Owner'");

                    b.ToTable("TenantMemberships");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentEntry", b =>
                {
                    b.HasOne("HeadlessCms.Api.Tenancy.Models.Tenant", null)
                        .WithMany("ContentEntries")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Content.Models.ContentType", "ContentType")
                        .WithMany("Entries")
                        .HasForeignKey("TenantId", "ProjectId", "ContentTypeId")
                        .HasPrincipalKey("TenantId", "ProjectId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Content.Models.ContentTypeVersion", "ContentTypeVersion")
                        .WithMany("Entries")
                        .HasForeignKey("TenantId", "ProjectId", "ContentTypeId", "ContentTypeVersionId")
                        .HasPrincipalKey("TenantId", "ProjectId", "ContentTypeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("ContentTypeVersion");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentField", b =>
                {
                    b.HasOne("HeadlessCms.Api.Content.Models.ContentTypeVersion", "ContentTypeVersion")
                        .WithMany("Fields")
                        .HasForeignKey("TenantId", "ProjectId", "ContentTypeVersionId")
                        .HasPrincipalKey("TenantId", "ProjectId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentTypeVersion");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentType", b =>
                {
                    b.HasOne("HeadlessCms.Api.Tenancy.Models.Tenant", "Tenant")
                        .WithMany("ContentTypes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Models.Project", "Project")
                        .WithMany("ContentTypes")
                        .HasForeignKey("TenantId", "ProjectId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Content.Models.ContentTypeVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("TenantId", "ProjectId", "Id", "CurrentVersionId")
                        .HasPrincipalKey("TenantId", "ProjectId", "ContentTypeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentTypeVersion", b =>
                {
                    b.HasOne("HeadlessCms.Api.Content.Models.ContentType", "ContentType")
                        .WithMany("Versions")
                        .HasForeignKey("TenantId", "ProjectId", "ContentTypeId")
                        .HasPrincipalKey("TenantId", "ProjectId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("HeadlessCms.Api.Models.Project", b =>
                {
                    b.HasOne("HeadlessCms.Api.Tenancy.Models.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.TenantInvitation", b =>
                {
                    b.HasOne("HeadlessCms.Api.Auth.Models.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeadlessCms.Api.Auth.Models.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Tenancy.Models.Tenant", "Tenant")
                        .WithMany("Invitations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.TenantMembership", b =>
                {
                    b.HasOne("HeadlessCms.Api.Tenancy.Models.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadlessCms.Api.Auth.Models.User", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeadlessCms.Api.Auth.Models.User", b =>
                {
                    b.Navigation("TenantMemberships");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentType", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("HeadlessCms.Api.Content.Models.ContentTypeVersion", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("HeadlessCms.Api.Models.Project", b =>
                {
                    b.Navigation("ContentTypes");
                });

            modelBuilder.Entity("HeadlessCms.Api.Tenancy.Models.Tenant", b =>
                {
                    b.Navigation("ContentEntries");

                    b.Navigation("ContentTypes");

                    b.Navigation("Invitations");

                    b.Navigation("Memberships");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
